name: Myfxbook Scraper

on:
  schedule:
      - cron: '0 */4 * * *'  # Esegue il job ogni 4 ore
  workflow_dispatch:  # Permette di avviare il workflow manualmente

jobs:
  scrape_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install selenium webdriver-manager

      - name: Run the scraper
        run: python scraper.py

      - name: Debug Mostra i file nel repository
        run: |
          ls -lah
          git status

      - name: Commit and push CSV file
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote remove origin || true
          git remote add origin https://x-access-token:${GH_TOKEN}@github.com/Hshs1993/myfxbook-scraper.git
          git fetch origin
          git checkout main
          git add myfxbook_data.csv
          git commit -m "Aggiornamento dati Myfxbook $(date '+%Y-%m-%d %H:%M:%S')" || echo "Nessuna modifica da commettere"
          GIT_ASKPASS=/bin/echo git push origin main || echo "Nessuna modifica da pushare"


