name: Myfxbook Scraper

on:
  schedule:
    - cron: '*/30 * * * *'  # Esegui ogni 30 minuti
  workflow_dispatch:  # Permette di avviarlo manualmente

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install selenium webdriver-manager pandas

      - name: Run Scraper
        run: python scraper.py

      - name: Upload CSV File
        uses: actions/upload-artifact@v4
        with:
          name: myfxbook-data
          path: myfxbook_data.csv
