name: Myfxbook Scraper

on:
  schedule:
    - cron: '*/10 * * * *'  # Esegui ogni 10 minuti
  workflow_dispatch:  # Permette di avviare manualmente l'azione

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install selenium
      - name: Install Chrome and ChromeDriver via APT
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable chromium-chromedriver
          echo "✅ Chrome e ChromeDriver installati con successo!"


      - name: Run scraper
        run: python scraper.py
      - name: Commit and Push CSV
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add myfxbook_data.csv
          git commit -m "Aggiornamento dati Myfxbook"
          git push
