name: Myfxbook Scraper

on:
  schedule:
    - cron: '0 * * * *'  # Esegue il job ogni ora
  workflow_dispatch:  # Permette di avviare il workflow manualmente

jobs:
  scrape_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install selenium webdriver-manager

      - name: Run the scraper
        run: python scraper.py

      - name: Commit and push CSV file
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git add myfxbook_data.csv
          git commit -m "Aggiornamento dati Myfxbook $(date '+%Y-%m-%d %H:%M:%S')" || echo "Nessuna modifica da commettere"
          git push origin main || echo "Nessuna modifica da pushare"
